FitnessBuddy/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitnessBuddy.Models
{
    public class Login
    {
        [Required]
        [StringLength(255, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "E-Mail")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        
    }
}

FitnessBuddy/Controllers/TrainerController.cs
using FitnessBuddy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace FitnessBuddy.Controllers
{
    public class TrainerController : Controller
    {
        ApplicationDbContext Db = new ApplicationDbContext();
        // GET: Trainer
        public ActionResult AdminHome()
        {
            return View();
        }

        public ActionResult ViewMemberList()
        {
            var List = Db.Members.ToList();
            return View(List);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            Program pro = Db.Programs.Single(x => x.id == id);
            return View(pro);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmation(int id)
        {
            Program pro = Db.Programs.Single(x => x.id == id);
            Db.Programs.Remove(pro);
            Db.SaveChanges();
            return RedirectToAction("ProgramList");
        }



        public ActionResult ProgramList()
        {
            var List = Db.Programs.ToList();
            return View(List);
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }


        [HttpPost]
        public ActionResult LogOff()
        {
            if (Session["username"] != null)
            {
                Session.Abandon();
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult AddProgram ()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProgram (Program prog)
        {

            Db.Programs.Add(prog);
            Db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        public ActionResult Edit(int id)
        {
            var memb = Db.Members.SingleOrDefault(c => c.Id == id);

            if (memb == null)
                return HttpNotFound();

            return View(memb);
        }

        [HttpPost]
        public ActionResult Update(Member memb)
        {
            var membInDb = Db.Members.Single(c => c.Id == memb.Id);

            membInDb.Password = memb.Password;
            membInDb.PhoneNumber = memb.PhoneNumber;
            membInDb.Goal = memb.Goal;
            membInDb.CurrentWeight = memb.CurrentWeight;
            membInDb.ConfirmPassword = memb.ConfirmPassword;
            membInDb.Birthdate = memb.Birthdate;
            membInDb.Email = memb.Email;
            membInDb.Full_Name = memb.Full_Name;

            Db.SaveChanges();
            return RedirectToAction("ViewMemberList");

        }


        public ActionResult EditProgram(int id)
        {
            var prog = Db.Programs.SingleOrDefault(c => c.id == id);

            if (prog == null)
                return HttpNotFound();

            return View(prog);
        }

        [HttpPost]
        public ActionResult Update(Program prog)
        {
            var progInDb = Db.Programs.Single(c => c.id == prog.id);


            progInDb.Type = prog.Type;
            progInDb.WorkOut_Plan = prog.WorkOut_Plan;
            progInDb.Training_Time = prog.Training_Time;
            progInDb.Supplments = prog.Supplments;

            Db.SaveChanges();
            return RedirectToAction("ProgramList");

        }
        [HttpGet]
        public ActionResult DeleteMember(int id)
        {
            Member mem = Db.Members.Single(x => x.Id == id);
            return View(mem);
        }
        [HttpPost]
        [ActionName("DeleteMember")]
        public ActionResult DeleteConfirm(int id)
        {
            Member mem = Db.Members.Single(x => x.Id == id);
            Db.Members.Remove(mem);
            Db.SaveChanges();
            return RedirectToAction("ViewMemberList");
        }

    }
}

FitnessBuddy/Views/Trainer/AddProgram.cshtml
@model FitnessBuddy.Models.Program

@{
    ViewBag.Title = "AddProgram";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Program</h2>

@using (Html.BeginForm("CreateProgram", "Trainer", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Program</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkOut_Plan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkOut_Plan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkOut_Plan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Training_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Training_Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Training_Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ProgramList")
</div>

FitnessBuddy/Views/Trainer/AdminHome.cshtml
@model FitnessBuddy.Models.Trainer

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>WELCOME ADMIN!</h2>

<p>This is the Admin Page. You can View, Edit or delete either a member or a program</p>
<br />



<a href="@Url.Action("ViewMemberList", "Trainer")" class="btn btn-primary btn-lg">View Members List</a>

<a href="@Url.Action("AddProgram","Trainer")" class="btn btn-primary btn-lg" color="orange">Add Program</a>

<a href="@Url.Action("ProgramList","Trainer")" class="btn btn-primary btn-lg" color="orange">View Programs</a>

FitnessBuddy/Views/Trainer/Delete.cshtml
@model FitnessBuddy.Models.Program

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Program</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkOut_Plan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkOut_Plan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Training_Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Training_Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplments)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ProgramList")
        </div>
    }
</div>

FitnessBuddy/Views/Trainer/DeleteMember.cshtml
@model FitnessBuddy.Models.Member

@{
    ViewBag.Title = "DeleteMember";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteMember</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Full_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentWeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            @Html.ActionLink("Back to List", "ViewMemberList")
        </div>
    }
</div>

FitnessBuddy/Views/Trainer/Edit.cshtml
@model FitnessBuddy.Models.Member

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Member</h2>

@using (Html.BeginForm("Update", "Trainer", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Member Data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Full_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentWeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentWeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentWeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>

        @Html.HiddenFor(model => model.Id)
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FitnessBuddy/Views/Trainer/EditProgram.cshtml
@model FitnessBuddy.Models.Program

@{
    ViewBag.Title = "EditProgram";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditProgram</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Program</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkOut_Plan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkOut_Plan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkOut_Plan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Training_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Training_Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Training_Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FitnessBuddy/Views/Trainer/Login.cshtml
@model FitnessBuddy.Models.Login
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Trainer", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FitnessBuddy/Views/Trainer/ProgramList.cshtml
@model IEnumerable<FitnessBuddy.Models.Program>

@{
    ViewBag.Title = "ProgramList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ProgramList</h2>

<p>
    @Html.ActionLink("Create New", "AddProgram")
</p>
<table class="table table-striped table-hover ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkOut_Plan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Training_Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplments)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr class="info">
    <td>
        @Html.DisplayFor(modelItem => item.Type)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.WorkOut_Plan)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Training_Time)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Supplments)
    </td>
    <td>
        @Html.ActionLink("Edit", "EditProgram", new { id = item.id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.id })
    </td>
</tr>
}

</table>

FitnessBuddy/Views/Trainer/ViewMemberList.cshtml
@model IEnumerable<FitnessBuddy.Models.Member>

@{
    ViewBag.Title = "ViewMemberList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ViewMemberList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped table-hover ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Full_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentWeight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Goal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="danger">
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConfirmPassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Full_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthdate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentWeight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Goal)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "DeleteMember", new { id=item.Id })
        </td>
    </tr>
}

</table>